<?php
declare(strict_types=1);

namespace Tests\TestCase\ORM\Postgres;

use Fyre\Core\Config;
use Fyre\Core\Container;
use Fyre\Core\Lang;
use Fyre\DB\Connection;
use Fyre\DB\ConnectionManager;
use Fyre\DB\Handlers\Postgres\PostgresConnection;
use Fyre\DB\Schema\SchemaRegistry;
use Fyre\DB\TypeParser;
use Fyre\Event\EventManager;
use Fyre\ORM\EntityLocator;
use Fyre\ORM\ModelRegistry;
use Fyre\Utility\Inflector;
use Fyre\Utility\Path;
use Tests\TestCase\ORM\Shared\ConnectionTrait;

use function getenv;

use const ROOT;

trait PostgresConnectionTrait
{
    use ConnectionTrait;

    protected static function buildContainer(): Container
    {
        $container = new Container();
        $container->singleton(TypeParser::class);
        $container->singleton(Config::class);
        $container->singleton(Inflector::class);
        $container->singleton(ConnectionManager::class);
        $container->singleton(SchemaRegistry::class);
        $container->singleton(ModelRegistry::class);
        $container->singleton(EntityLocator::class);
        $container->singleton(EventManager::class);
        $container->singleton(Lang::class);
        $container->use(Config::class)
            ->set('App.locale', 'en')
            ->set('Database', [
                'default' => [
                    'className' => PostgresConnection::class,
                    'host' => getenv('POSTGRES_HOST'),
                    'username' => getenv('POSTGRES_USERNAME'),
                    'password' => getenv('POSTGRES_PASSWORD'),
                    'database' => getenv('POSTGRES_DATABASE'),
                    'port' => getenv('POSTGRES_PORT'),
                    'charset' => 'utf8',
                ],
            ]);

        $container->use(Lang::class)
            ->addPath(Path::join(ROOT, 'lang'));

        return $container;
    }

    protected static function createSchema(Connection $db): void
    {
        $db->query(<<<'SQL'
            CREATE TABLE cascade_parents (
                id INTEGER NOT NULL,
                PRIMARY KEY (id)
            )
        SQL);

        $db->query(<<<'SQL'
            CREATE TABLE cascade_children (
                id INTEGER NOT NULL,
                cascade_parent_id INTEGER NULL,
                PRIMARY KEY (id),
                FOREIGN KEY (cascade_parent_id) REFERENCES cascade_parents (id) ON DELETE RESTRICT
            )
        SQL);

        $db->query(<<<'SQL'
            CREATE TABLE items (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                name VARCHAR(255) NULL DEFAULT NULL,
                PRIMARY KEY (id)
            )
        SQL);

        $db->query(<<<'SQL'
            CREATE TABLE composite_items (
                tenant_id INTEGER NOT NULL,
                id INTEGER NOT NULL,
                name VARCHAR(255) NULL DEFAULT NULL,
                PRIMARY KEY (tenant_id, id)
            )
        SQL);

        $db->query(<<<'SQL'
            CREATE TABLE contains (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                item_id INTEGER NOT NULL,
                contained_item_id INTEGER NOT NULL,
                PRIMARY KEY (id)
            )
        SQL);

        $db->query(<<<'SQL'
            CREATE TABLE others (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                value INTEGER NOT NULL,
                PRIMARY KEY (id)
            )
        SQL);

        $db->query(<<<'SQL'
            CREATE TABLE timestamps (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                created TIMESTAMP NOT NULL,
                modified TIMESTAMP NOT NULL,
                PRIMARY KEY (id)
            )
        SQL);

        $db->query(<<<'SQL'
            CREATE TABLE users (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                name VARCHAR(255) NULL DEFAULT NULL,
                deleted TIMESTAMP NULL DEFAULT NULL,
                PRIMARY KEY (id)
            )
        SQL);

        $db->query(<<<'SQL'
            CREATE TABLE addresses (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                user_id INTEGER NOT NULL,
                address_1 VARCHAR(255) NULL DEFAULT NULL,
                address_2 VARCHAR(255) NULL DEFAULT NULL,
                suburb VARCHAR(255) NULL DEFAULT NULL,
                state VARCHAR(255) NULL DEFAULT NULL,
                deleted TIMESTAMP NULL DEFAULT NULL,
                PRIMARY KEY (id)
            )
        SQL);

        $db->query(<<<'SQL'
            CREATE TABLE posts (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                user_id INTEGER NULL DEFAULT NULL,
                title VARCHAR(255) NULL DEFAULT NULL,
                content TEXT NULL DEFAULT NULL,
                deleted TIMESTAMP NULL DEFAULT NULL,
                PRIMARY KEY (id)
            )
        SQL);

        $db->query(<<<'SQL'
            CREATE TABLE comments (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                user_id INTEGER NULL DEFAULT NULL,
                post_id INTEGER NULL DEFAULT NULL,
                content TEXT NULL DEFAULT NULL,
                deleted TIMESTAMP NULL DEFAULT NULL,
                PRIMARY KEY (id)
            )
        SQL);

        $db->query(<<<'SQL'
            CREATE TABLE tags (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                tag VARCHAR(255) NULL DEFAULT NULL,
                PRIMARY KEY (id)
            )
        SQL);

        $db->query(<<<'SQL'
            CREATE TABLE posts_tags (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY,
                post_id INTEGER NOT NULL,
                tag_id INTEGER NOT NULL,
                value INTEGER NULL DEFAULT NULL,
                PRIMARY KEY (id)
            )
        SQL);
    }
}
